# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-09 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0063_auto_20180108_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_tweeted',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
